# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param b the number of burn-in length
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' XC <- myGibbsC(5000,1000)
#' }
#' @export
myGibbsC <- function(N, b) {
    .Call('_StatComp21074_myGibbsC', PACKAGE = 'StatComp21074', N, b)
}

